### PR TITLE
Update webpack.config.ts

### PR DESCRIPTION
**Pull request by mauman**
added permission <all_urls> to Firefox

### CODE REVIEW

**Comment by firsttris** [comment]
you can test you changes by installing the latest release: https://github.com/firsttris/chrome.sendtokodi/releases/download/0.0.46/sendToKodi-firefox-0.0.46.zip

i pushed it to firefox store.

**Comment by mauman** [comment]
Hi,
I tried it both locally and by downloading the latest version from the Firefox store.
Unfortunately, the problem is still there.
As I said, I am not an expert in browser extension development.
Here is a snapshot of the extension debug window when I try to ping Kodi from the extension preferences:

image

Basically, it says CORS failed, and that could be the problem.
But I cannot understand why it is happening.
The Kodi remote control interface does not have SSL enabled, but that seems fine for Chrome; maybe that is the problem with Firefox?
I googled around to check how to enable SSL on the Kodi remote interface. Honestly, I have no idea how to do that...

**Comment by mauman** [comment]
Another update: I tried to enable SSL on the Kodi side, and added self-generated certificates.
In this way, the remote control window works with https, but the error in the extension changed to "CORS Missing Allow Origin" (see below).

image

**Comment by firsttris** [comment]
Copilot says: 

To fix the CORS preflight failure in your Firefox addon, you can try expanding the `host_permissions` and ensuring the correct headers are sent. Here is an example of how to adjust the manifest and background scripts:

### Manifest (manifest.json)
Ensure you have the correct permissions and host permissions:

```json
{
  "name": "SendToKodi",
  "description": "Send almost every stream from your Browser to Kodi with SendToKodi",
  "short_name": "SendToKodi",
  "options_ui": {
    "page": "options.html"
  },
  "permissions": [
    "tabs",
    "storage",
    "webRequest",
    "webRequestBlocking"
  ],
  "host_permissions": [
    "http://*/*",
    "https://*/*"
  ],
  "icons": {
    "16": "icons/icon16.png",
    "48": "icons/icon48.png",
    "128": "icons/icon128.png"
  },
  "background": {
    "service_worker": "background.js"
  },
  "action": {
    "default_popup": "popup.html"
  },
  "manifest_version": 3,
  "version": "0.0.17"
}
```

### Background Script (background.js)
Add a background script to set the CORS headers:

```javascript
chrome.webRequest.onHeadersReceived.addListener(
  function(details) {
    let headers = details.responseHeaders;
    headers.push({name: "Access-Control-Allow-Origin", value: "*"});
    headers.push({name: "Access-Control-Allow-Methods", value: "GET, POST, PUT, DELETE, OPTIONS"});
    headers.push({name: "Access-Control-Allow-Headers", value: "Content-Type, Authorization"});
    return {responseHeaders: headers};
  },
  {urls: ["<all_urls>"]},
  ["blocking", "responseHeaders"]
);
```

### Explanation:
- **manifest.json**: Adds `webRequest` and `webRequestBlocking` to the permissions to modify headers.
- **background.js**: Sets the CORS headers for all requests.

Make sure to place the files correctly in your addon project and reload the addon to apply the changes.

**Comment by firsttris** [comment]
Im pretty sure in chrome its just a matter of correct permissions & host permissions

**Comment by firsttris** [comment]
background script sounds fictional

**Comment by firsttris** [comment]
https://stackoverflow.com/questions/49075878/firefox-extension-request-is-interpreted-as-cors

maybe in firefox we need background.js script. see last post.

**Comment by firsttris** [comment]
here it says you need to add all_urls to host_permissions not to permissions:

https://stackoverflow.com/questions/75700847/how-to-deal-with-cors-error-when-writing-firefox-plugin

**Comment by mauman** [comment]
I added a new pull request.
In the meantime, I searched more online, and it seems that the problem is caused by the CORS pre-flight request made automatically by Firefox, while Chrome does not do it.
That can be avoided using a simple request: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests
Would it be possible to use simple requests in the extension?

**Comment by mauman** [comment]
Another way could be to change the request mode by setting it to "no-cors": https://developer.mozilla.org/en-US/docs/Web/API/Request/mode

**Comment by firsttris** [comment]
you can test on your machine, and if you found a solution we can release it

**Pull request merged**
